//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessCode
    {
        public int CodeID { get; set; }
        public string AccessCode1 { get; set; }
        public Nullable<System.DateTime> GenerationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    }
}
