//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int ShipmentID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> PartID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
    
        public virtual Part Part { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
