//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseTransaction
    {
        public int IDtransaction { get; set; }
        public int sparePartID { get; set; }
        public int quantity { get; set; }
        public string operationType { get; set; }
        public System.DateTime transactionDate { get; set; }
    
        public virtual SparePart SparePart { get; set; }
    }
}
